### ISSUE TITLE
No artboard are added

### ISSUE THREAD

**Issue by tdwesten** [herrhelms/social-artboards-sketch#6]
Hi, after installing your plugin and running it from the menu no artboard's are added to my artboard section. 

<img width="1552" alt="schermafdruk 2017-02-17 12 39 43" src="https://cloud.githubusercontent.com/assets/224501/23064077/48790372-f50e-11e6-8d5f-12be032ee19b.png">

**Comment by herrhelms** [comment]
Hi, thanks for reporting I have heard that many people have a problem with my plugin lately. I tried to recreate your issue with the most recent version and was successful upon opening a second untitled document and then rechecking the artboards ... sadly sketch >4.x will then override the groups name to "Custom" - I'm trying to reach out to the core dev team. You can read more about the problem here: https://medium.com/@herrhelms/feature-proposal-adding-more-custom-preset-groups-to-sketch-59c367d20f57

**Comment by jsgv** [comment]
Same issue here. 😢

**Comment by nonfungibletunji** [comment]
same issue here

**Comment by jeancharlesamey** [comment]
🤔 great idea, but same issue,
any news or hack ?

**Comment by qmarcos** [comment]
Another one added to the request :)

**Comment by itsjohnnie** [comment]
Same issue here.

**Comment by herrhelms** [comment]
I just updated the plugin here on github. Please download and see if the new version works for you. Happy to hear back from you! Closing this for now...
